CHANGES.txt, app/scripts/controllers/cluster.js, app/scripts/services/stats.js, app/styles/theme.less, app/views/node.html
and display number of cores per node
Note: this feature will require Crate 0.52.x
=> show relative Crate process CPU usage

CHANGES.txt, app/scripts/controllers/common.js, app/scripts/services/udc.js
Both user id and cluster id are anonymous traits.
You can disable UDC via the `udc.enabled` setting on the Crate server.
=> UDC: identify anonymous user with cluster id.

CHANGES.txt, app/scripts/controllers/feed.js
even when the `udc.enabled` setting was enabled on the Crate server
=> version check was always fetched with `udc.enabled=false`

CHANGES.txt, app/scripts/controllers/console.js, app/views/console.html
when two or more columns with the same name were selected
=> fix: column headers where not shown in result table on console page

CHANGES.txt, app/scripts/app.js, app/scripts/controllers/cluster.js, app/views/nodelist.html
cluster overview to avoid rendering errors
if there are more than one nodes with the same name
=> use id instead of name to address nodes in

CHANGES.txt, app/scripts/services/sql.js, app/scripts/services/stats.js
in cases when Crate is served at a different location than ``/``, e.g. when proxied to a subdirectory such as ``/crate/`` then also the ``_sql`` endpoint is located at ``/crate/_sql``.
This change removes the hard coded path and resolves the correct location of ``_sql`` based on the relative location to ``/_plugin/crate-admin/``.
=> resolve path to ``/_sql`` endpoint correctly

app/scripts/services/sql.js
in order to also allow urls with trailing slash, such as
`http://localhost:4200/` as valid `base_uri` parameter for local
development
=> trim trailing slash from base_uri parameter

CHANGES.txt, app/scripts/controllers/console.js
two things were not working properly:
1. if the index of the recentQueries is too high it returned "undefined" and resulted in this error:
2. the recentQueries array was always inconsistent and didn't store the last query typed (in the sa,e session)
@chaudum please review
=> fix: history doesn't work properly

CHANGES.txt, app/scripts/controllers/overview.js
this error occurs when you change the `route` from/to  the `overview` page, the `window.onresize()` event is triggered and nvd3 cannot calculate the size.
this seems to be fixed in the current nvd3 [version](https://github.com/novus/nvd3/blob/master/src/utils.js#L71). But the version requested by angular-nvd3-directives is much [older](https://github.com/angularjs-nvd3-directives/angularjs-nvd3-directives/blob/master/bower.json#L28) 
@chaudum please review
=> solved chart onresize error

CHANGES.txt, app/scripts/app.js
@chaudum please review 
I think the preferred language that was detected overwrites the fallback language in this line: https://github.com/angular-translate/angular-translate/blob/1f7ec6548e301261810e81ad13e7148400f2be4a/src/service/translate.js#L512
=> add english as fallback

CHANGES.txt, bower.json, package.json
http://g.recordit.co/zMwW7GDZjd.gif
`LIMIT 100` must be applied automatically.
`LIMIT 100` must be applied automatically.
loaded into console. Another ARROW-UP reveals `SELECT * FROM tweets;`
http://g.recordit.co/of90R52Sxt.gif
=> Mk/0.21.2 - preparing release 0.21.2

app/scripts/app.js, app/scripts/services/sql.js
the Synchronous XMLHttpRequest was previously used to lazy load the plugin modules. it's replaced with a promise. 
if the plugins fail to load the app will be loaded anyway and display a warning.
test 1: successful loading
http://g.recordit.co/G0AyBOWsxo.gif
test 2: plugin loading error (by supplying a wrong url in conf/plugings.json)
http://g.recordit.co/UGn0WB8Tox.gif
=> remove logs and warnings

app/styles/common.less, app/styles/statusbar.less
This fixes an issue that was occurring in Chromium and Firefox on Xubuntu, where the page was larger than the viewport horizontally if a scrollbar was present. It seems like the scrollbar was being considered part of the viewport, so that `100vw` was actually *bigger* than the viewport. Changed to use `100%` instead, which fixes this.
=> Fixed linux viewport issue

Gruntfile.js, package.json
to be able to bind dev server to 0.0.0.0
so the admin ui can be opened from another device
(e.g. windows virtual box)
make sure you run `bin/npm update`!
=> updated grunt-contrib-connect dependency

app/scripts/controllers/common.js, app/styles/nav.less, app/views/nav.html
navigation tooltip position was previously overwritten by other jquery tooltip placements
` $("[rel=tooltip]").tooltip({
placement: 'bottom'
});`
=> fix tooltip position

app/scripts/controllers/tables.js
fixes broken navigation introducted with https://github.com/crate/crate-admin/commit/8986823e52264e6bdd35778e67578fc55ad2baf5
=> redirect to correct table URL if just /tables

CHANGES.txt, app/scripts/services/stats.js
Caused following JS error:
```
16:38:09.323 Error: nodeLoad is null
prepareLoadInfo@http://localhost:9000/scripts/services/stats.js:107:9
refreshState/<@http://localhost:9000/scripts/services/stats.js:173:23
processQueue@http://localhost:9000/bower_components/angular/angular.js:13318:27
scheduleProcessQueue/<@http://localhost:9000/bower_components/angular/angular.js:13334:27
$RootScopeProvider/this.$get</Scope.prototype.$eval@http://localhost:9000/bower_components/angular/angular.js:14570:16
$RootScopeProvider/this.$get</Scope.prototype.$digest@http://localhost:9000/bower_components/angular/angular.js:14386:15
$RootScopeProvider/this.$get</Scope.prototype.$apply@http://localhost:9000/bower_components/angular/angular.js:14675:13
done@http://localhost:9000/bower_components/angular/angular.js …
```
=> do not try to append load if load info from node is missing

Gruntfile.js
in `grunt server` task, css was bundled in /styles/main.css. It should be /static/styles/main.css
=> fix css loading from the right location in grunt server task

CHANGES.txt, app/styles/console.less
=> Console now resizes to show all of the query

CHANGES.txt, app/index.html, app/scripts/app.js, app/scripts/controllers/feed.js, app/scripts/services/utils.js, app/tests/services/parseIsoDatetime.test.js, app/views/statusbar.html
```javascript
item.timestamp = new Date(item.date);
console.log(item.date);
console.log($filter('date')(item.date));
console.log(item.timestamp);
console.log($filter('date')(item.timestamp));
```
in Safari this returns :
```
[Log] 2016-12-02T14:08:24+0000 (feed.js, line 97)
[Log] Dec 2, 2016 (feed.js, line 98)
[Log] Invalid Date (feed.js, line 99)
[Log] Invalid Date (feed.js, line 100)
```
apparently item.date which has the format ([ISO 8601](https://en.wikipedia.org/wiki/ISO_8601)) `2015-02-26T16:27:15+0000` is invalid in Safari which uses ([rfc3339](https://tools.ietf.org/html/rfc3339#section-5.8))
from Safari's console:
``` javascript
> new Date('2015-02-26T16:27:15+0000')
< Invalid Date
> new Date('2015-02-26T16:27:15+00:00')
< Thu Feb 26 2015 17:27:15 GMT+0100 (CET)
```
=> fixed notification date formatting in safari

app/plugins/monitoring/monitoring.js
an error occurs when the query_type is not in the list. for example "CREATE"
to reproduce (in master), run crate with enterprise license set to true,
create tweets table >
the monitoring plugin will not work anymore
=> fix monitoring plugin bug

CHANGES.txt, app/styles/console.less
looks like a known issue of Codemirror https://github.com/codemirror/CodeMirror/issues/3770#issuecomment-172492500
=> fixed issue that caused codemirror text to appear on top of settings tab

CHANGES.txt, app/views/formatted-object-template.html
@m-kharbat Should this be backported to 1.1 and 1.2?
=> Fixed formatting of arrays within objects

CHANGES.txt, app/plugins/monitoring/monitoring.html
Just waiting on @jodok as to whether this approach is what we want. I thought adding this here, and then information on the performance penalty of collecting stats in the config documentation, would be the right approach - as all users, not just enterprise ones, can enable stat collection and will want to know about its effect on performance.
=> Updated the stat collection warning for monitoring.

CHANGES.txt, app/styles/overview.less
adjusted toggle buttons so that they are not broken when the user is using zoom (3 values around 100%)
before:
after:
http://g.recordit.co/W9Gp70WuZz.gif
=> fix toggle buttons display on zoom

CHANGES.txt, app/scripts/filter/text.js, app/tests/filter/text.test.js
=> fix timestamp formatting in console to use the same default formatting as date_format()

CHANGES.txt, app/scripts/controllers/common.js, app/views/statusbar.html
This is due to our decision to shift away from building seperate documentation for each hotfix release, and to instead only build for feature releases.
=> Changed documentation link to x.y link instead of x.y.z

CHANGES.txt, app/plugins/tutorial/tutorial.js
wrong property was accessed. column is now being filled.
=> fixed twitter tutorial empty account_user column

CHANGES.txt, app/scripts/controllers/overview.js, app/views/console.html, app/views/overview.html
I think the issue is related to the $digest cycle, so it seems that the chart waits for the next cycle to be displayed..
So I'm not sure if this is the best solution, but it does make the chart display faster
=> fixed an issue that cause the overview chart to be slow to display

app/index.html, app/scripts/controllers/cluster.js, app/scripts/controllers/common.js, app/scripts/controllers/overview.js, app/scripts/controllers/tables.js, app/scripts/services/checks.js, app/scripts/services/clusterEventsHandler.js, app/scripts/services/stats.js, app/scripts/services/tableinfo.js, app/tests/services/stats.tests.js, app/tests/services/tableinfo.tableList.test.js
create ClusterEventsHandler service
use $q.all in stats.js to reduce event triggers
update TableList service to use already available shardInfo data
-----
the table TableList service was querying the 4 shardInfo queries every 5sec, even though the ClusterState service was doing the same.
I also joined all the promises in stats.js under a $q.all, in order to notify the controllers only once, (and not every time one of those promises is successful/or failed)
=> create ClusterEventsHandler service

CHANGES.txt, app/plugins/shards/shards.css, app/plugins/shards/shards.html, app/plugins/shards/shards.js
=> replicated shards in the unassigned row of the Shards view are now grouped by id

CHANGES.txt, app/scripts/controllers/cluster.js
required for CrateDB 2.3
system/user/stolen values have been deprecated and return -1
=> updated CPU graph to use value from os['cpu']['used']

CHANGES.txt, app/scripts/controllers/tables.js, app/views/tablelist.html
this issue was introduced with the one-time binding commit. solved by adding `ng-if="renderSidebar"` to force re-rendering the table list
=> Fixed an issue that caused the table list to display wrong results

LICENSE, NOTICE
following the official Apache guide:
http://www.apache.org/dev/licensing-howto.html
steps I took:
- started from two files:
- LICENCE containing an unmodified version of the Apache License 2.0
- NOTICE containing the standard Crate.io legal boilerplate
- added copyright and license information for "bits we're bundling" to the end of the LICENSE file
- this meant moving some stuff from bootstrap.py (which is totally fine, and I left a note there, as is required by their licence)
- it also meant dropping many of the things we were already listing, because, I poked around, and as far as I can tell, we are not directly "bundling those bits". we rely on the end user to fetch those bits when she is building the project. so there's no requirement for us to mention them in these files
this is …
=> fix up LICENCE and NOTICE

CHANGES.txt, app/scripts/controllers/tables.js, app/scripts/controllers/views.js, app/views/tablelist.html, app/views/viewlist.html
When filtering the table/view list, the incorrect link, table status and table size would be preserved from what was previously in that position in the table/view list. This fix changes this so that the links/status/size are updated as we would expect.
The clear filter button also was not working. This has also been fixed.
This should fix #560
=> Fixed several issues concerning table/view filtering

CHANGES.txt, app/app.module.js
so the admin ui can also be served from locations other than `/`
=> load plugins.json from relative URL

CHANGES.txt, app/scripts/filter/text.js, app/tests/filter/text.test.js
=> fixed an issue that caused timestamp to not be formatted correctly

CHANGES.txt, app/app.module.js
Use license information available under ``sys.cluster.license`` instead
to distinguish between enterprise and community edition.
=> Remove usage of deprecated `license.enterprise`

DEVELOP.rst
The node-sass package needs to be installed first, before the rest
of the packages are installed.
=> Update developer documentation for package dependencies for node.

CHANGES.rst, app/scripts/controllers/tables.js
information_schema.table_partitions.schema_name was renamed
to information_schema.table_partitions.table_schema in CrateDB
4.0.0
=> Rename schema_name to tables_schema in tables partion query

CHANGES.rst, app/scripts/controllers/tables.js
is_generated changed in 4.0 from a boolean to a string (`ALWAYS`,
`NEVER`) to conform to the SQL standard.
Fixes https://github.com/crate/crate-admin/issues/634
=> Adapt column query for `is_generated` change in CrateDB 4.0

CHANGES.rst, app/plugins/tutorial/tutorial.js
since angular router uses /#!/ the twitter query string was not found in window.location.search
it is instead found in window.location.hash
=> Fixed an issue that cause the twitter tutorial to not be automatically started

CHANGES.rst, app/styles/views/_console.scss
setting position:sticky already stacks the header on top of other elements
=> removed unnecessary z-index from pagination header.

CHANGES.rst, app/views/table-detail.html
`if (var)` is false for empty strings, null, undefined, false, 0 and
NaN. We want to display `NULL` only for the `null` case, not any of the
others.
Before:
After:
=> Fix partitioned by column value display

CHANGES.rst, app/plugins/shards/static/i18n/de.json, app/plugins/shards/static/i18n/en.json, app/plugins/shards/static/i18n/es.json
It's a minor fix to keep the UI tab labels uniformed and capitalized.
Currently, all of them are started with a capital letter except `shards`.
=> Fix capitalization of shards tab label

CHANGES.rst, app/scripts/controllers/tables.js, app/scripts/services/tableinfo.js
The partitioned by columns are fetched from `information_schema.tables`
where the column names use a dot notation:
select partitioned_by from information_schema.tables where table_name = 'test';
+----------------+
| partitioned_by |
+----------------+
| ["pk.part"]    |
+----------------+
These column names were then used to lookup the value from the `values`
in `information_schema.table_partitions`, but there the columns have the
subscript notation:
select values from information_schema.table_partitions where table_name = 'test';
+---------------------+
| values              |
+---------------------+
| {"pk['part']": "x"} |
+---------------------+
Fixes https://github.com/crate/crate-admin/issues/657
=> Fix value display for nested partitioned columns

CHANGES.rst, app/plugins/tutorial/tutorial.js, docs/conf.py
This, previously, would cause deprecated error messages on the CrateDB node due to the use of the `TIMESTAMP` type.
=> Tweet tutorial table no longer uses deprecated column types

docs/help.rst, docs/index.rst
Previously, the :last-reviewed: metadata was added to indicate that these files
received a content refresh.
Per <crate/tech-writing-domain#360>, we are now using Git commit keywords.
=> Minor copyedit for files, including removal of :last-reviewed: metadata

.github/workflows/docs.yml, .travis.yml
replace Travis CI (docs tests only) with GitHub Actions workflow - based on https://github.com/crate/crash/pull/341#issuecomment-700773923
This change reverts `.travis.yml` to the version prior to the addition of the
docs tests (i.e., bdbaa967d31c43d3ec35bd9457c6b5cbd1c30a3c).
todo list:
=> Replace Travis CI docs tests with GitHub Actions workflow

.gitignore, .mergify.yml, docs/Makefile, docs/build.json
this PR is a sub-task of https://github.com/crate/tech-writing-domain/issues/353
changes:
- Pins the docs-build to 0.4.0
- Updates the Mergify configuration to require the docs tests (added in https://github.com/crate/crate-admin/commit/68824e2aaab2fa334159eb37c2baa69ea7f5141b)
=> Upgrade to new build 0.4.0

app/plugins/tutorial/tutorial.html
Hi there,
while I recognize CrateDB has been conceived before the advent of Rust's Cargo package manager and its ecosystem of Crates, we might want to adjust to reality that the tags on Stack Overflow associated with `crate` are more related to Rust these days and update this to use the tag `cratedb` instead. [1] shows that this space is already well populated.
While it might still be appropriate to use filesystem locations like `/var/lib/crate` to refer to directories where CrateDB is operated within local namespaces (https://github.com/crate/crate-howtos/pull/268), we should adjust this on public spaces like Stack Overflow in order to educate ourselves and our users.
Andreas.
[1] https://stackoverflow.com/tags/cratedb
=> Tutorial: Use "cratedb" tag when linking to Stack Overflow

CHANGES.rst, app/scripts/controllers/tables.js, app/scripts/controllers/views.js
Hi there,
@faymarie reported #700 the other day, thank you. This patch might fix it.
I believe the selection of the "current" table/view has gotten new code already. Having redirection code in a function which gets called when registered to the `STATE_REFRESHED` event is probably a bad idea as exactly this might produce the observed behavior.
While everything should usually be fine, I can imagine an edge case where this event handler will not get detached when the page/view object is destroyed by navigating to another page. In this case, the event might fire in the background when a new table is added by another arbitrary operation potentially run by another user. And - there you go - the UI will swap out the current page and display the "Tables" page.
As I haven't been able to observe …
=> Remove misguided redirects which may lose queries currently being typed

.github/workflows/docs.yml, README.rst, docs/build.json
Hi Naomi,
this patch will bring the new 1.0.0 release of `crate-docs` to `crate-admin`. Vale's prose linter tripped and I've implemented its suggestion. Good job.
Andreas.
=> Use crate-docs version 1.0.0 and add a suggestion from prose linting

.github/workflows/tests.yml, CHANGES.rst, app/scripts/controllers/tables.js, app/scripts/controllers/views.js
add quoteIdent() and isReservedKeyword()
closes #714 
- ~~Add quoteIdent function to table controller~~
- ~~Add isReservedKeyword function to table controller~~
- ~~Adapt render function to use quoteIdent to only quote identifiers when needed~~
- Add new lines before `FROM` and `LIMIT` in render function
- Add whitespace between identifiers
- Use server-side `quote_ident()` function when fetching column-names
=> adapt table render function

.github/workflows/docs.yml, .github/workflows/tests.yml, DEVELOP.rst, README.rst
Hi there,
following some other repositories, this patch will rename the default branch to `main`. Is there any other thing to do beyond merging this and actually renaming the branch on GitHub, @norosa?
Andreas.
=> Rename default branch to "main"

CHANGES.rst, app/scripts/controllers/console.js, app/styles/styles.scss, app/styles/views/_console.scss, app/vendor.module.js
- Remove min-width for columns in console to reduce scrolling
- Change syntax highlighting in console. Keywords in double quotes are now longer  highlighted. Types are highlighted with a different color.
- Activated codemirror code hints for keywords
closes #710
=> improvements to console / codemirror configuration

CHANGES.rst, app/scripts/filter/numbers.js
Use correct binary prefixes (e.g. KiB, MiB, GiB) for units of data in UI.
No change in calculation.
=> Use correct binary prefixes for units of data

CHANGES.rst, app/scripts/controllers/views.js
Fix generated queries for views containing identifiers that need to be quoted.
Identifiers that need to be quoted (e.g. with upper case letters or reserved keywords) were double quoted twice
This bug was introduced with https://github.com/crate/crate-admin/pull/715 😬 
@jayeff
=> Fix generated queries for views containing identifiers that need to be quoted

DEVELOP.rst, devtools/create_tag.sh
Hi there,
I just minted release 1.19.1, which needed a few updates to the release guidelines and the `./devtools/create_tag.sh` helper program.
Andreas.
=> Fix and improve release guidelines and helper program

CHANGES.rst, app/plugins/monitoring/static/icons/icon-monitoring.svg, app/styles/vars/_dark-theme-variables.scss, app/styles/vars/_light-theme-variables.scss, app/styles/views/_nav.scss
side-nav: fix monitor icon color + make slightly smaller + hover-effect
=> side-nav: fix monitor icon color + make slightly smaller

CHANGES.rst, app/views/formatted-array-template.html
Added ability to correctly display nested arrays in OBJECT(IGNORED) columns
fixes #744
=> Added ability to correctly display nested arrays

package-lock.json
Hi there,
while preparing the next release 1.20.0, I ran into this:
> `npm install --package-lock-only` showed a warning and recommended to run `npm audit fix`.
This is the corresponding patch.
Andreas.
=> Address non-breaking vulnerability warnings

package-lock.json
This patch, created with `npm audit fix`, addresses those issues:
- https://github.com/crate/crate-admin/security/dependabot/20
- https://github.com/advisories/GHSA-xvch-5gv4-984h
=> Mitigate issue about "minimist" addressed by Dependabot

docs/Makefile, docs/build.json
Will bring Sphinx 5 to the documentation sandbox.
=> Update to crate-docs 2.1.0

CHANGES.rst, app/scripts/controllers/views.js
While rendering the view list, the `updateViewList()` must be called
to ensure that the previous selected view is used as the current
state may not be updated already.
This issue only happen when the selection is done fast while still
initializing the view tab.
Fixes #775.
=> Fix view list rendering issue which caused a jump to the default view

CHANGES.rst, app/styles/views/_common.scss, app/styles/views/_console.scss
- **Fit console query results in viewport**
This should make it easier to work with wider result-sets, as one does not longer need to scroll to the bottom of the page to use the horizontal scrollbar
- **Fix: Adjust scrollbar corner color to fit with theme**
was white before / didn't fit with rest of theme
- [ x ] [CLA](https://crate.io/community/contribute/cla/) is signed
=> Fit console query results in viewport

CHANGES.rst, app/scripts/controllers/console.js
- Fixed formatting of ``TIMESTAMP WITHOUT TIME ZONE`` values in query console 
result table.
**_prev:_**
**_now:_**
=> Fixed formatting of timestamp values in console

CHANGES.rst, DEVELOP.rst, package-lock.json, package.json
Hi,
this patch updates some dependency packages Dependabot recently reported about.
- engine.io
- loader-utils
- minimatch
- socket.io
`npm audit fix` has been used beforehand, and then `minimatch` has manually been added to the `overrides` section within `package.json`, concluded by another `npm install --package-lock-only`, in order to update `package-lock.json`.
Andreas.
=> Update dependencies with critical updates

package-lock.json, package.json
This patch bumps all runtime dependency packages to their most recent compatible patch releases.
```
npm update bootstrap bootstrap-sass codemirror font-awesome jquery json3 oclazyload popper.js
npm update @uirouter/angularjs angular angular-cookies angular-nvd3 angular-sanitize angular-translate angular-translate-loader-partial angular-translate-loader-static-files angular-translate-storage-cookie
```
After the build/test process croaked on something related to `bootstrap-sass`, 5ea784e6c4 was implemented after discovering a corresponding recommendation at https://github.com/twbs/bootstrap-sass/issues/1224#issuecomment-1054518213. Thanks, @AprilArcus.
=> Chore: Update runtime dependencies across the board

package-lock.json, package.json, webpack.dev.config.js, webpack.prod.config.js
- A successor patch to #794. Created by adjusting `package.json` a bit, and then running `npm update`. 
- `npm audit` output did not significantly change, so I assume the items within the `overrides` section have not been needed.
=> Chore: Update development dependencies

package-lock.json, package.json
Updating to node-sass version 8 is apparently now possible, after updating to Node.js 16 with 7bc6a745315, and the `sass` package with 074e56eb26. This addresses GHSA-r8f7-9pfq-mjmv.
=> Update development dependency `node-sass` to version 8

.github/workflows/tests.yml, .mergify.yml, DEVELOP.rst, package.json
Following up on #796, this patch updates the sandbox/build/CI environment to use Node.js 18.
`NODE_OPTIONS=--openssl-legacy-provider` was needed to satisfy `webpack@4`.
- [Error message "error:0308010C:digital envelope routines::unsupported"](https://stackoverflow.com/a/69699772)
- https://github.com/webpack/webpack/issues/14532#issuecomment-947012063
- https://github.com/nodejs/node/issues/40455#issuecomment-1123071147
The real solution is to update to `webpack@5`.
- https://github.com/webpack/webpack/issues/14532#issuecomment-1324340823
=> Sandbox/CI: Update to Node.js 18

DEVELOP.rst, bootstrap.sh
The new `bootstrap.sh` is intended for both development and Jenkins, in order to fix https://github.com/crate/crate-alerts/issues/424.
_We need this because the sandbox environment of Admin UI got modernized to use Node.js 18 now, see https://github.com/crate/crate-admin/pull/797._
=> CI: Add an universal sandbox bootstrap program

CHANGES.rst, app/scripts/controllers/overview.js, app/tests/services/monitoring/monitoringQueryService.test.js
CrateDB 5.2 needs `AVG(ended::bigint - started::bigint)` instead of `AVG(ended - started)`.
=> Fixed monitoring statement for compatibility with CrateDB 5.2

.readthedocs.yml, CHANGES.rst, app/views/statusbar.html, docs/build.json
Before:
After:
Checked: Regular versions also still show successfully after the change
=> Fix additional whitespace in snapshot version (and readthedocs)

README.rst, app/plugins/tutorial/tutorial.html, app/scripts/controllers/common.js, app/scripts/controllers/feed.js, app/tests/controllers/feed.test.js, app/views/table-detail.html, app/views/tables.html, app/views/views.html, docs/_extra/robots.txt
Adjust links: crate.io became cratedb.com, coming from GH-819.
=> Adjust links: crate.io became cratedb.com

karma.conf.js, package-lock.json, package.json
PhantomJS is deprecated since ages.
> On the NPM registry, the most recent release of PhantomJS, `phantomjs-prebuilt`, is 6 years old already.
- Resolves GH-830.
- https://github.com/crate/crate-admin/pull/802#issuecomment-1370020374
- [Replace PhantomJS with Headless Chromium for JavaScript Unit Testing in Karma](https://medium.com/@alexbainter/replace-phantomjs-with-headless-chromium-for-javascript-unit-testing-in-karma-59812e6f8ce4)
=> Tests: Use Chromium instead of PhantomJS with Karma testing

DEVELOP.rst
The CrateDB sandbox recently switched from Gradle to Maven. This patch accounts for that.
=> Sandbox: Update development docs about changes to the release process

package.json
Removed unnecessary "--openssl-legacy-provider" argument, which was required for webpack@4
Now crate-admin successfully runs on windows after clean installation
Closes #846
=> Removed "--openssl-legacy-provider" from package.json

package-lock.json
Just usual irregular maintenance. What the title says.
List of affected packages: body-parser, cookie, http-proxy-middleware, ip, path-to-regexp, send, tar, webpack.
Intends to mitigate a few warning items on any security scanners (GitHub, OCI image, you name it) that might be used on software artefacts today down the line.
Might also overlap with some Dependabot PRs, so merging this PR may resolve a few of them already.
- GH-849
- GH-852
- GH-854
- GH-856
- GH-858
- GH-859
=> Dependencies: Update dependency packages using `npm audit fix`

webpack.dev.config.js, webpack.prod.config.js
After updating to webpack 5, the build/test invocation introduced a few warnings.
- GH-861
Follow the advice to not use `style-loader` and `mini-css-extract-loader` together.
- https://github.com/webpack-contrib/mini-css-extract-plugin/issues/613#issuecomment-707653736
=> Sandbox: Fix update to webpack 5

docs/cluster.rst, docs/console.rst, docs/help.rst, docs/monitoring.rst, docs/privileges.rst, docs/shards.rst, docs/tables.rst, docs/views.rst
The in-page TOC is redundant as it's also present to the right side.
"Screenshot" headline seems a bit silly, so removed that.
=> Docs: remove in page toc

docs/index.rst
Overall the intent is to remove any "noise" that before getting started.
* GH admonition is secondary and is therefore moved to the bottom.
* The local TOC is removed as it's redundant with the local TOC being in the right navbar now.
* The Tip for using the Rest API isn't really so relevant here. If anything, we could consider it at the bottom, but why then not mention the CLI if it's alternatives we want to mention?
=> Docs: index.rst: Minor page tuning
