CHANGES.txt
app/scripts/controllers/tables.js

fixed bug that showed custom schemas multiple times

---

CHANGES.txt
app/scripts/controllers/feed.js

because issue has been fixed on server side

reverted last commit

---

app/index.html
app/scripts/controllers/overview.js
app/scripts/services/stats.js
app/styles/theme.less
app/views/overview.html
bower.json

- updated cluster overview live diagram with new js chart library

New graph feature

---

app/index.html
app/scripts/controllers/overview.js
app/scripts/services/stats.js
app/styles/theme.less
app/views/overview.html
bower.json

Revert "New graph feature"

---

CHANGES.txt
app/scripts/controllers/tables.js
app/styles/theme.less
app/views/tables.html

added partition values to "Partitions" table

---

app/scripts/services/stats.js

requires https://github.com/crate/crate/pull/2111

used probe_timestamp for IOPs calculation

---

CHANGES.txt
app/scripts/controllers/cluster.js
app/views/node.html

crate process graph update

---

CHANGES.txt
app/scripts/services/tableinfo.js

which lead to different results when viewing on admin ui on different nodes

approx number of underrepl/missing records was calculated incorrectly

---

CHANGES.txt
app/scripts/controllers/console.js
app/scripts/services/stats.js
app/views/console.html

fix cluster not reachable

---

CHANGES.txt
app/scripts/controllers/tables.js
app/scripts/services/tableinfo.js

exposed shard states and relocating/recovering shards in `sys.shards` table

updated calculation of underreplicated shards/records to work with newly

---

CHANGES.txt
app/scripts/controllers/tables.js
app/scripts/services/shardinfo.js
app/scripts/services/stats.js
app/scripts/services/tableinfo.js
app/views/tables.html

added recovery status to table info

---

CHANGES.txt
app/scripts/services/tableinfo.js

broke calculations for partitioned tables causing table partitions not showing up

fix: change in calculation of recovery percentage

---

CHANGES.txt
app/scripts/services/shardinfo.js
app/scripts/services/tableinfo.js

relocating shards where previously displayed as "underreplicated" shards
causing a yellow cluster state while relocating was in progress

do not count relocating shards as "underreplicated" shards

---

CHANGES.txt
app/scripts/services/stats.js

fixed read of undefined property

---

Gruntfile.js
bower.json
package.json

this required grunt-contrib-less instead of deprecated grunt-recess

updated Bootstrap to latest 3.x version

---

CHANGES.txt
app/scripts/controllers/feed.js
app/views/statusbar.html

load additional links in menu dynamically

---

app/scripts/controllers/feed.js
app/scripts/services/udc.js

see also https://github.com/crate/crate-web/pull/396

updated analytics tokens of URLs in dropdown menu

---

CHANGES.txt
app/scripts/controllers/common.js

Fixed menu order and added missing translation

---

CHANGES.txt
app/scripts/services/tableinfo.js

fix: number of underreplicated shards canot be negative

---

app/i18n/de.json
app/i18n/en.json
app/styles/sb-admin.less
app/views/console.html

update styling of the error trace

---

app/scripts/services/sql.js
app/scripts/services/stats.js

use storedURI properly to display log message

---

CHANGES.txt
bower.json
package.json

prepate release 0.19.1

---

CHANGES.txt
bower.json
package.json

preparing release 0.19.1

---

CHANGES.txt
bower.json
package.json

updated changelog to reflect release 0.19.1

---

CHANGES.txt
bower.json
package.json

preparing release 0.20.0

---

app/styles/sb-admin.less
app/views/console.html

format error trace inside <pre><code>

---

CHANGES.txt
app/styles/sb-admin.less
app/views/tablelist.html

added a button to clear the search in the table list view

---

CHANGES.txt
app/views/nav.html

fix for this issue https://github.com/crate/crate-admin/issues/236
@chaudum please review

corrected logo url

---

CHANGES.txt

introduced in fe3b47c3a463d142d28c25385da48fa10f4bad73

removed incorrect entry from changelog

---

CHANGES.txt
app/views/nav.html

@m-kharbat fix for fix https://github.com/crate/crate-admin/commit/284c87b8cf7a2add51ed12fefab1d7bf7d3702fe :(

fixed hyperlink on logo in navigation

---

CHANGES.txt
app/scripts/services/sql.js
app/scripts/services/stats.js

reduce logs

---

CHANGES.txt
app/scripts/controllers/console.js

fixed broken execute button

---

CHANGES.txt
app/scripts/controllers/tables.js
app/scripts/services/shardinfo.js
app/scripts/services/tableinfo.js

https://github.com/crate/crate-admin/issues/251

fix : tables view shows 0 tables

---

CHANGES.txt
app/views/node.html

http://g.recordit.co/JCFUKkZjLj.gif

fixed unsafe REST URL in nodes view

---

app/scripts/controllers/common.js
app/scripts/controllers/overview.js
app/scripts/filter/text.js
app/styles/common.less
app/styles/dark-theme-variables.less
app/styles/light-theme-variables.less
app/styles/main.less
app/styles/nav.less
app/styles/overview.less
app/styles/statusbar.less
app/styles/theme.less
app/tests/filter/text.test.js
app/views/nav.html
app/views/overview.html
app/views/statusbar.html

implement overview

---

app/scripts/controllers/tables.js
app/scripts/services/tableinfo.js
app/styles/common.less
app/styles/dark-theme-variables.less
app/styles/light-theme-variables.less
app/styles/main.less
app/styles/tables.less
app/styles/theme.less
app/views/tables.html

Implement tables view

---

app/scripts/filter/text.js
app/scripts/services/nodeinfo.js
app/styles/common.less
app/styles/dark-theme-variables.less
app/styles/light-theme-variables.less
app/styles/main.less
app/styles/nodelist.less
app/styles/tablelist.less
app/tests/filter/text.test.js
app/views/nodelist.html
app/views/tablelist.html

Implement nodelist

---

app/styles/common.less
app/styles/main.less
app/styles/node.less
app/views/node.html
app/views/tables.html

Implement node

---

app/scripts/controllers/console.js
app/scripts/controllers/overview.js
app/scripts/filter/text.js
app/styles/common.less
app/styles/console.less
app/styles/dark-theme-variables.less
app/styles/light-theme-variables.less
app/styles/main.less
app/styles/theme.less
app/tests/filter/text.test.js
app/views/console.html

Checklist:
http://g.recordit.co/cogZ4skgfE.gif

implement console

---

app/index.html
app/scripts/app.js
app/scripts/controllers/common.js
app/styles/common.less
app/styles/statusbar.less
app/views/nav.html
app/views/statusbar.html

http://g.recordit.co/qpGlcgHVZ8.gif

implement menu icon

---

app/scripts/app.js
app/styles/common.less
app/styles/statusbar.less
app/styles/theme.less
app/views/node.html
app/views/nodelist.html
app/views/statusbar.html
app/views/tables.html

http://g.recordit.co/9uILZ7nfqT.gif

toggle table/nodes lists

---

app/plugins/tutorial/tutorial.html
app/styles/common.less
app/styles/dark-theme-variables.less
app/styles/light-theme-variables.less
app/styles/main.less
app/styles/tutorial.less

Implemented tutorial

---

app/scripts/controllers/cluster.js
app/scripts/controllers/overview.js
app/scripts/services/stats.js
app/styles/charts.less
app/styles/dark-theme-variables.less
app/styles/light-theme-variables.less
app/styles/main.less
app/styles/overview.less
app/styles/statusbar.less
app/views/overview.html

updated overview graph to new design

---

app/views/overview.html

unified indentation in overview.html

---

app/index.html

to conform to new naming
@celaus can you please review!

updated title of index.html to CrateDB Admin UI

---

app/styles/console.less
app/styles/nodelist.less
app/styles/tablelist.less
app/views/nodelist.html

@m-kharbat Please review! I think all the font sizes now match the design docs - i dont know if we want to scale font sizes down further on smaller screens or not though.

Reviewed ++ fixed font sizes

---

DEVELOP.rst

update DEVELOP.rst to show that bildout supports python3.5

---

app/i18n/de.json
app/i18n/en.json
app/i18n/es.json
app/scripts/controllers/common.js
app/scripts/controllers/feed.js
app/scripts/filter/text.js
app/styles/console.less
app/styles/dark-theme-variables.less
app/styles/light-theme-variables.less
app/styles/nav.less
app/styles/statusbar.less
app/views/statusbar.html

implement notify btn

---

app/scripts/controllers/overview.js
app/views/overview.html

before : 
http://recordit.co/R3UMYfnI8I
after: 
http://g.recordit.co/ryOQrbVh5O.gif

fix load btns

---

CHANGES.txt
app/scripts/app.js

Angular's $location.search() does not reliably work in hashbang URL mode
see https://github.com/angular/angular.js/issues/1521
@m-kharbat please

fixed base_uri for development mode

---

CHANGES.txt
app/scripts/controllers/feed.js
app/tests/controllers/feed.test.js
app/tests/services/navigationService.test.js

also use same pattern of jsonp loading for all other json urls
@Autophagy please

fixed newsfeed

---

app/styles/overview.less

fix load wrap

---

app/styles/dark-theme-variables.less
app/styles/light-theme-variables.less

unify colors

---

app/styles/common.less
app/styles/nodelist.less
app/styles/overview.less
app/styles/tablelist.less
app/styles/tables.less
app/styles/tutorial.less

Minor Fixes

---

app/scripts/controllers/console.js

Removed semi colon check when shift+enter in console

---

app/styles/overview.less
app/views/overview.html

make flex-basis smaller for cluster checks

---

app/styles/nodelist.less
app/views/nodelist.html

updated version highlighting in nodelist to new design

---

app/styles/common.less
app/styles/dark-theme-variables.less
app/styles/light-theme-variables.less
app/styles/nav.less
app/styles/statusbar.less
app/views/nav.html
app/views/statusbar.html

http://g.recordit.co/gMVTE2IQhf.gif

add backdrop to close sidenav

---

CHANGES.txt
app/scripts/controllers/tables.js

default display of the first table in the table list

---

CHANGES.txt

Prepare release 0.21.3

---

CHANGES.txt

several changelog entries were incorrectly added to CHANGES.txt file
introduced in 39e4cd28d7bc02bb70a1aba331df2f065927986d

cleaned changelog

---

.jshintrc
.travis.yml
Gruntfile.js
app/scripts/app.js
app/scripts/controllers/cluster.js
app/scripts/controllers/common.js
app/scripts/controllers/console.js
app/scripts/controllers/feed.js
app/scripts/controllers/overview.js
app/scripts/controllers/tables.js
app/scripts/filter/numbers.js
app/scripts/filter/text.js
app/scripts/services/checks.js
app/scripts/services/nodeinfo.js
app/scripts/services/shardinfo.js
app/scripts/services/sql.js
app/scripts/services/stats.js
app/scripts/services/tableinfo.js
app/scripts/services/translation.js
app/scripts/services/udc.js

run `bin/grunt jshint`
jshint is also run before travis tests
@m-kharbat and @Autophagy please

Improved code quality by using JSHint

---

CHANGES.txt
app/scripts/controllers/cluster.js

redirect to first or selected node

---

Gruntfile.js
app/index.html
app/plugins/tutorial/tutorial.js
bower.json

it is only used in the tutorial plugin
plugins should not have any additional dependencies
also cleaned up code (jshint)
@m-kharbat and @mikethebeer please

remove purl dependency

---

bower.json

upgrade angular to 1.5.8

---

CHANGES.txt
app/plugins/tutorial/tutorial.js
app/scripts/app.js
app/scripts/services/sql.js

do not store base_uri permanently in localStorage

---

app/tests/services/checks.tests.js
app/tests/services/shardinfo.test.js

added tests for checks.js

---

app/tests/services/health.tests.js

add tests for health.js

---

CHANGES.txt
bower.json
package.json

prepare release 1.0.0

---

CHANGES.txt
bower.json
package.json

update changelog to reflect admin-ui 1.0.0

---

CHANGES.txt
Gruntfile.js
app/scripts/controllers/common.js
app/scripts/services/sql.js
app/styles/dark-theme-variables.less
app/styles/light-theme-variables.less
app/views/statusbar.html

@chaudum please review
http://g.recordit.co/07Puo8e8em.gif

fix images urls and base uri

---

CHANGES.txt
app/styles/overview.less

fix radio btn position

---

CHANGES.txt
app/scripts/controllers/common.js

http://g.recordit.co/WiPP1CGTRa.gif 
fix admin-ui support, @celaus should disable the intercom chat icon before this is released
@Autophagy please review

fix intercom support

---

CHANGES.txt
app/scripts/controllers/console.js
app/styles/common.less
app/styles/console.less
app/styles/dark-theme-variables.less
app/styles/light-theme-variables.less
app/views/console.html

show loading indicator when execute query is in progress

---

app/scripts/app.js

added stylesheet asynch loading for plugins.
tested by adding a tutorial.css file with a background-red class, and by adding "stylesheet" to the plugins config

load plugin stylesheets asynch

---

CHANGES.txt
app/scripts/controllers/console.js
app/scripts/services/datatypechecks.js
app/static/i18n/de.json
app/static/i18n/en.json
app/static/i18n/es.json
app/styles/console.less
app/views/console.html

display waring when query result contains an unsafe number

---

.gitignore
Gruntfile.js

updated gruntfile to post codecov on pr.
updated gitignore to ignore /coverage files

add coverage to git ignore and fix codecov

---

.jshintrc
Gruntfile.js
app/index.html
app/scripts/app.js
app/scripts/controllers/overview.js
app/views/overview.html
bower.json

i updated the charting library to https://github.com/krispo/angular-nvd3 which is better maintained and uses a later version of nvd3
http://g.recordit.co/xH6ygH5EoE.gif

update charting library to angular-nvd3

---

app/scripts/controllers/cluster.js
app/views/node.html

update node graphs to angular-nvd3

---

app/styles/common.less
app/styles/dark-theme-variables.less
app/styles/light-theme-variables.less
app/styles/overview.less
app/views/overview.html

update css for monitoring plugin

---

app/scripts/app.js
app/scripts/controllers/overview.js
app/styles/common.less
app/styles/dark-theme-variables.less
app/styles/light-theme-variables.less
app/styles/overview.less
app/views/overview.html

updated the styling to fit the new chart style

Admin ui monitoring

---

CHANGES.txt
app/styles/console.less

Capitalise keywords in SQL console

---

CHANGES.txt
app/scripts/filter/text.js
app/tests/filter/text.test.js
app/views/console.html

Added external link for formatted geoshape results

---

CHANGES.txt
app/scripts/controllers/console.js
app/tests/controllers/console.test.js
app/views/console.html
app/views/editor.html

Added a CrateDB mimetype, instead of using plsql

---

CHANGES.txt
app/views/console.html

using ng-if instead of ng-show forces the element to rerender

fix horizontal scrolling issue in the console results

---

CHANGES.txt
app/scripts/controllers/tables.js
app/styles/common.less
app/styles/tablelist.less
app/views/tablelist.html

http://g.recordit.co/qHdvyZpbgT.gif

Added buttons to collapse and expand all schemas in the tables view

---

CHANGES.txt
app/scripts/controllers/cluster.js
app/styles/common.less
app/styles/nodelist.less
app/styles/tablelist.less
app/views/nodelist.html
app/views/tablelist.html

fixed issue that caused node list and table list not be scrollable

Fixed issue that caused the last element in the side-bar to be hidden

---

CHANGES.txt
app/scripts/controllers/console.js

rerender results table whith every query execution

---

CHANGES.txt
app/scripts/controllers/common.js
app/scripts/services/stats.js

fix issue that caused  cluster offline not to be displayed

---

CHANGES.txt
app/views/statusbar.html

added node number to the status bar

---

CHANGES.txt
app/scripts/controllers/common.js
app/scripts/controllers/overview.js

@m-kharbat Do you think this needs to be backported?

Removed odd behaviour with load readings on Windows

---

CHANGES.txt
app/scripts/services/sql.js
app/views/console.html

@m-kharbat Does this need cherrypicking into 1.2?

Added fallback if no result types are recieved

---

CHANGES.txt
app/scripts/services/tableinfo.js

fix partitions health issue

---

CHANGES.txt

for consistency with crate/crate#5187

minor formatting improvements for CHANGES

---

CHANGES.txt

for consistency with crate/crate#5216

fix up CHANGES

---

CHANGES.txt
app/plugins/monitoring/monitoring.js
bower.json

fix y-axis number formatting in monitoring plugin

---

CHANGES.txt
Gruntfile.js
app/index.html
app/scripts/app.js
app/scripts/controllers/common.js
app/styles/statusbar.less
app/views/statusbar.html
bower.json

display license.ident in the admin-ui

---

CHANGES.txt
app/styles/common.less
app/styles/tablelist.less

display long table names correclty

---

CHANGES.txt
app/styles/console.less

change color of the console keywords

---

CHANGES.txt
app/scripts/app.js
app/scripts/controllers/common.js
app/styles/overview.less
app/styles/statusbar.less
app/views/statusbar.html

display username in the admin-ui when the enterprise edition is enabled

---

CHANGES.txt
app/plugins/tutorial/tutorial.html
app/plugins/tutorial/tutorial.js
app/styles/tutorial.less

http://g.recordit.co/lvrp8lTr6b.gif

display error message in the tutorial page

---

CHANGES.txt
app/plugins/privileges/privileges.html
app/plugins/privileges/userList.html
app/styles/common.less

http://g.recordit.co/HwInEBOLDe.gif

Fixed an issue in the privileges view that caused the users list not to be scrollable and removed visible scroll bar

---

CHANGES.txt
app/scripts/services/sql.js
app/tests/services/sqlQuery.test.js

add row count to query status

---

CHANGES.txt
app/scripts/controllers/tables.js
app/styles/tables.less
app/views/tables.html

show generation expression in tables view

---

bower.json

upgrade codeMirror

---

CHANGES.txt
app/scripts/controllers/console.js
app/scripts/controllers/tables.js
app/styles/tables.less
app/views/tables.html

http://g.recordit.co/rYNat3jjAJ.gif

Added query table button to table view

---

.travis.yml
Gruntfile.js
package.json

fixed travis build that was failing in master because of codecov

fix travis build

---

CHANGES.txt
app/conf/plugins.json
app/plugins/shards/nodeContentTmpl.html
app/plugins/shards/shardContentTmpl.html
app/plugins/shards/shards.css
app/plugins/shards/shards.html
app/plugins/shards/shards.js
app/plugins/shards/static/i18n/de.json
app/plugins/shards/static/i18n/en.json
app/plugins/shards/static/i18n/es.json
app/plugins/shards/static/icons/icon-shards.svg
app/scripts/controllers/common.js
app/styles/common.less
app/styles/console.less
app/styles/dark-theme-variables.less
app/styles/light-theme-variables.less

implement shards visualization

---

CHANGES.txt
app/scripts/controllers/common.js

before : 
http://g.recordit.co/w6RYb6VNw6.gif
after : 
http://g.recordit.co/SrLx3AbluC.gif

fixed custom tooltip position

---

CHANGES.txt
app/plugins/shards/shards.html
app/plugins/shards/shards.js

remove the one time binding in this view because it prevented from seeing the relocation

on demand loading of shard and node data

---

CHANGES.txt
app/scripts/controllers/console.js

http://g.recordit.co/FJKEAkbAjX.gif

keep input of console when changing tabs

---

CHANGES.txt
app/scripts/services/datatypechecks.js
app/views/formatted-object-template.html

this issue https://github.com/crate/crate-admin/issues/486 is already fixed in master

Fixed issue that caused NULL values to be displayed as empty object

---

CHANGES.txt
app/scripts/services/sql.js

use correct state name for redirection to /401

fixed /401 redirection

---

app/plugins/monitoring/monitoring.js
app/plugins/shards/shards.js

- Use clusterEventHandler instead of $rootscope
- trigger service refresh from the controller instead of recursion , in order to be able to stop it from the controller.
- cancel intervals when view is destroyed

stop service intervals when the view is destroyed

---

CHANGES.txt
app/views/console.html

< pre > tag doesn't ignore spaces like the rest of html

fixed an issue that caused extra spaces to be displayed in the console results

---

CHANGES.txt
app/scripts/controllers/common.js

analytics variable is not available when certain addblockers are enabled

fixed an issue that caused the statusbar not to be displayed if the user has an addblocker enabled

---

CHANGES.txt
app/plugins/shards/shards.js

show all nodes even those without shards

---

app/scripts/controllers/tables.js

remove delay in displaying the tables list

add initial calls to update table list

---

CHANGES.txt
app/scripts/controllers/tables.js
app/scripts/services/shardinfo.js

fix issue that caused closed partitions to show critical data health

---

CHANGES.txt
app/styles/console.less

finally fixed this and tested with a mouse

 Remove horizontal scroll from the console editor

---

CHANGES.txt
app/views/node-detail.html
app/views/nodelist.html
app/views/overview.html
app/views/statusbar.html
app/views/table-detail.html

remove one-time binding from translated strings, since it prevented updating the string to a different language

Fix an issue that caused the translation strings to not be loaded correctly

---

docs/requirements.txt

this is needed by RTD. forgot to include it before

add missing requirements.txt for RTD

---

CHANGES.txt
app/app.components.js
app/app.module.js
app/plugins/privileges/userList.html
app/scripts/constants/auth.js
app/scripts/constants/client.js
app/scripts/controllers/authentication.js
app/scripts/controllers/feed.js
app/scripts/services/apollo.provider.js
app/styles/views/_statusbar.scss
app/vendor.module.js
app/views/statusbar.html
app/views/tablelist.html
karma.conf.js
package-lock.json
package.json

implement authentication feature in the admin-ui

---

CHANGES.txt
app/scripts/controllers/tables.js
app/views/tablelist.html

limited the search filter to the fqn and removed one-time binding

Updated the table list search to filter tables only by fqn

---

app/scripts/services/sql.js

this issue concerns only master, which is not released so it doesn't need a changes entry

Fixed an issue that caused the console query status to not be correct.

---

CHANGES.txt
app/plugins/shards/shards.js
app/scripts/services/shardinfo.js

See https://github.com/crate/crate/pull/6972

Adapt queries for the _node -> node column name change

---

docs/index.txt

I am adding blocks like this to all docs projects

add link to GitHub

---

package-lock.json
package.json

update karma should fix the hoek package security issue

updated karma to 2.0.2

---

docs/help.txt
docs/index.txt

okay let's try again on a different project 😬
I just added a new set of styles for admonitions in the docs. I am now going through each docs project and improving our use of admonitions

improve use of admonitions

---

app/app.module.js

Linked to: https://github.com/crate/crate/pull/7875

Support CrateDB sys.cluster.license['expiryDate'] field name change

---

app/app.module.js

adjust license information query to use the new field names

---

CHANGES.txt
app/plugins/monitoring/monitoring.js
app/plugins/privileges/privileges.js
app/plugins/shards/shards.js
app/plugins/tutorial/tutorial.js
app/scripts/controllers/common.js
app/views/nav.html

fixed an issue that caused incorrectness in icon highlighting

---

CHANGES.txt
app/app.module.js
app/scripts/controllers/common.js
app/views/statusbar.html

Note that this will only work with 3.3.0+ and 4.0.0+
Do we mention the compatibility somewhere?

Update license display to include max nodes.

---

package-lock.json
package.json

upgrade bootstrap to 4.3.1

---

.mergify.yml

Add mergify integration

---

docs/cluster.txt
docs/index.txt
docs/monitoring.txt
docs/tables.txt

Changes headers from title case to sentence case. Also cuts out an issue where a subsection 'Features' within monitoring.txt was introduced that consisted of no content.

Changes headers to sentence case

---

.travis.yml
package-lock.json
package.json

upgrade node-sass and fix travis.yml

---

CHANGES.rst
package.json

Prepare release 0.15.2

---

CHANGES.rst
package-lock.json
package.json

prepare release 1.15.3

---

CHANGES.rst
app/scripts/controllers/tables.js

Fixed issue in nested-column identification regex

---

CHANGES.rst
app/scripts/controllers/console.js
app/scripts/filter/text.js
app/scripts/services/datatypechecks.js
app/tests/filter/text.test.js
app/tests/services/datatypechecks.tests.js
app/views/console.html

Add results formatting for new Time with Timezone type

---

docs/help.rst

Fix typos in tweet import doc

---

.vscode/settings.json
docs/_extra/robots.txt

https://github.com/crate/tech-writing-domain/issues/11#issuecomment-680053782

Change sitemap name to site.xml

---

docs/help.rst
docs/index.rst

Add reviewed metadata to updated docs

---

.mergify.yml

if you don't specify both, mergify will work when at least one passes

Specify both GitHub Actions docs checks

---

DEVELOP.rst
package.json

Hi there,
this is an overhaul of "DEVELOP.rst". The patch brings in a better document structure and a more concise walkthrough in order to get started in development mode more quickly.
Andreas.

Improve DEVELOP.rst

---

CHANGES.rst
package-lock.json
package.json

Release 1.18.0

---

CHANGES.rst
app/styles/views/_common.scss

Change browser scrollbar appearance to fit with rest of UI

---

CHANGES.rst
app/scripts/controllers/tables.js

Add length limit for varchar(n) and bit(n) types in table view
closes #727

Add length limit for varchar(n) and bit(n) types in table view

---

package-lock.json
package.json

Another round of chores after #763.

Update a few other dependency packages to satisfy npm

---

.github/workflows/tests.yml
DEVELOP.rst

Hi,
this is just a minor patch to bump `npm` to its most recent version.
Andreas.

Update build environment to use most recent version of npm@8.5.5

---

package-lock.json

Again.
- https://github.com/advisories/GHSA-cfm4-qjh2-4765

Bump "node-forge" package to address security advisory

---

CHANGES.rst
package-lock.json

- Angular 1.8.3
- Async 2.6.4
- sass-loader 10.3.1
References: GHSA-fwr7-v2mv-hh25

Chore: Updated a few JavaScript dependencies

---

.readthedocs.yml

Chore: Upgrade RTD build to Python 3.8

---

CHANGES.rst
package-lock.json
package.json

New release with improvement #778 by @proddata. Thanks!

Release 1.23.0

---

package-lock.json
package.json

Upgrade the [`scss-tokenizer`](https://www.npmjs.com/package/scss-tokenizer) library to the most recent version.

Chore: Upgrade to scss-tokenizer-0.4.3

---

CHANGES.rst
package-lock.json
package.json

Running a patch release including the fix #781 by @proddata.

Release 1.23.1

---

package-lock.json
package.json

This will resolve GHSA-w573-4hg7-7wgq.

Update dependency package `decode-uri-component`

---

CHANGES.rst
package-lock.json
package.json

Maintenance release with dependency package updates, ...
- `npm update decode-uri-component` (GHSA-w573-4hg7-7wgq)
- `npm update bootstrap bootstrap-sass codemirror font-awesome jquery json3 oclazyload popper.js`
- `npm update @uirouter/angularjs angular angular-cookies angular-nvd3 angular-sanitize angular-translate angular-translate-loader-partial angular-translate-loader-static-files angular-translate-storage-cookie`
... and updated toolchain.
- Fix dependency problems with `bootstrap-sass^3.4` by using newer `node-sass^8.0.0`.
- Sandbox/CI: Update to Node.js 18.

Release 1.24.1

---

CHANGES.rst
DEVELOP.rst
package-lock.json
package.json

Let's cut another release with the enhancements by @hammerhead on behalf of GH-806.
/cc @seut

Release 1.24.2

---

CHANGES.rst
DEVELOP.rst
package-lock.json
package.json

The release patch for the accompanying fix for CrateDB 5.2.
- GH-809

Release 1.24.3

---

CHANGES.rst

Just shipping a few dependency updates.

Release 1.24.4

---

app/static/i18n/de.json
app/static/i18n/en.json
app/static/i18n/es.json
app/static/i18n/fr.json
app/static/i18n/it.json

This patch brings in the update to a few texts on the »Help« page from https://github.com/crate/crate-admin/issues/819#issuecomment-1814507923. Thanks, @michaelkremmel.

Help: Copy-editing a few texts and their translations

---

app/static/i18n/es.json

Follow up to https://github.com/crate/crate-admin/pull/826

Fix grammar in ES version of DISCOURSE_MSG

---

CHANGES.rst
package-lock.json
package.json

Release 1.24.7

---

.github/workflows/tests.yml
bootstrap.sh

Now, after GH-831, updating to Node.js 20 is easily possible.

Sandbox: Update to Node.js 20 and NPM 10

---

package-lock.json

GH-802 unlocks another wave of updates provided by `npm audit fix`.

Dependencies: Another wave of updates provided by `npm audit fix`

---

.readthedocs.yml
docs/build.json

Chore: Fix docs build by upgrading to crate-docs 2.1.2

---

package-lock.json
package.json

- Invoke `npm audit fix`, which updated `cross-spawn`.
- Update to most recent version of `ws`.
- Update to most recent version of `braces`.
- https://github.com/crate/crate-admin/security/dependabot
Software tests succeed. Needs manual testing to be 100% sure nothing goes south, see GH-878.

Dependency updates 2024-11
